Contacts  section -mobile version with some questions
IvanovArtemNA/ice-cream-team-project-1 pull request #36
Opened 2022-10-10 19:03 UTC by Wonderband

1.  Прописав загальні класи  section та container - відповідно до того, що сказав вчора увечері Ярослав. Тобто від 320 до 480 - тягнеться, на 480 - фіксується. Зробив аутлайн для наглядності. Потім приберемо.
2. Кнопки - не зрозумів, що там з ховером та фокусом, взяв стиль з ваших секцій, але треба уточнити, як заливати кнопки.
3. Не спозиціював вертикально текст CAFE на жовтій лейблі - щось туплю, як вирівняти текст в div по вертикалі. Треба загорнути в додатковий блочний тег, типу р? Чи якось простіше можна? 

Може ще щось забув - після коментів поправлю все разом

2022-10-10 21:08 UTC, IvanovArtemNA requested changes

2022-10-11 07:29 UTC, Wonderband commented on src/sass/layout/_contacts.scss
> +.contacts__text-block:not(:last-child)::after {
Задав, але там висота нуль, тому різниці наче немає. Чи потрібен тут зайвий код та властивість?

2022-10-11 07:31 UTC, Wonderband commented on src/partials/contacts.html
> +                <div class="contacts__subtitle">cafe</div>
Інлайн флекс - гарна ідея!
Але висота все одно потрібна, бо інакше чомусь збільшує висоту до 22рх

2022-10-11 07:34 UTC, Wonderband commented on src/partials/contacts.html
> -                    <p class="contacts__text--normal">+61(0) 383 766 284</p>
Паддінги поки що не міняю, бо треба зрозуміти стиковку секцій. Можливо, має сенс задавати падінги тільки зверху чи знизу на кожному контейнері? Тобто, треба затвердити якусь загальну логіку вертикальних падінгів всередині контейнерів.
Це версія тільки до 768, тобто мобайл. Після затвердження одразу ж дороблю інші.

На рахунок тексту не зрозумів, про яку секцію мова. Оскільки від 320 до 480 тягнеться контейнер, то текст стрибає відповідно да заданих падінгів.

2022-10-11 07:43 UTC, Wonderband commented on src/partials/contacts.html
> -                    <p class="contacts__text--normal">+61(0) 383 766 284</p>
На ділянці між 320 до 480 ця секція взагалі неочевидна - я зробив так, що кожна картка тягнеться аж до 480рх, і відповідно текст адреси кожної картки витягується в 1 рядок. І до 768 залишається таким же, витягнутим. Це наче логічно, бо сказано, щоб тягнулося все до 480, а потім фіксувалося. Але дизайн виходжить такий собі. Але Ярослав сказав, що це проблема дизайнера))

2022-10-11 08:10 UTC, merged